In [1]:
import pandas as pd
import numpy as np

In [2]:
data = np.random.randn(4,3)

In [3]:
df = pd.DataFrame(data)

In [4]:
df

          0         1         2
0  0.431152  0.416453  1.184432
1 -0.493698  1.061889  0.379888
2  0.827030 -0.177320  1.496683
3 -0.159509 -1.057945 -1.931546

In [5]:
type(df)

pandas.core.frame.DataFrame

In [6]:
new_df = pd.DataFrame(data,index=["atil","zeynep","atlas", "mehmet"], columns = ["salary","age","seniority"])

In [7]:
new_df

          salary       age  seniority
atil    0.431152  0.416453   1.184432
zeynep -0.493698  1.061889   0.379888
atlas   0.827030 -0.177320   1.496683
mehmet -0.159509 -1.057945  -1.931546

In [9]:
new_df[["age"]]

             age
atil    0.416453
zeynep  1.061889
atlas  -0.177320
mehmet -1.057945

In [10]:
new_df.loc["atil"]

salary       0.431152
age          0.416453
seniority    1.184432
Name: atil, dtype: float64

In [11]:
new_df.iloc[0]

salary       0.431152
age          0.416453
seniority    1.184432
Name: atil, dtype: float64

In [12]:
new_df["extra"] = 10

In [14]:
new_df

          salary       age  seniority  extra
atil    0.431152  0.416453   1.184432     10
zeynep -0.493698  1.061889   0.379888     10
atlas   0.827030 -0.177320   1.496683     10
mehmet -0.159509 -1.057945  -1.931546     10

In [15]:
new_df.drop("extra",axis=1)

          salary       age  seniority
atil    0.431152  0.416453   1.184432
zeynep -0.493698  1.061889   0.379888
atlas   0.827030 -0.177320   1.496683
mehmet -0.159509 -1.057945  -1.931546